- name: Add the user 'girls'
  ansible.builtin.user:
    name: girls
    groups: wheel
    append: yes
    state: present



- name: Creating ssh directory
  file:
    path: /home/girls/.ssh
    state: directory
    owner: girls
    group: girls
    mode: '0700'

- name: Copy key 1
  copy:
    src: ssh_private
    dest: /home/girls/.ssh
    owner: girls
    group: girls

- name: Copy key 2
  copy:
    src: ssh_public
    dest: /home/girls/.ssh
    owner: girls
    group: girls